-- MySQL Script generated by MySQL Workbench
-- Mon Nov  9 21:20:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sis_imperio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sis_imperio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sis_imperio` DEFAULT CHARACTER SET utf8 ;
USE `sis_imperio` ;

-- -----------------------------------------------------
-- Table `sis_imperio`.`tipo_estabelecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_imperio`.`tipo_estabelecimento` (
  `idtipo_estabelecimento` INT NOT NULL AUTO_INCREMENT,
  `tipoEstabelecimento` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipo_estabelecimento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis_imperio`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_imperio`.`estoque` (
  `idestoque` INT NOT NULL AUTO_INCREMENT,
  `nome_estoque` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idestoque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis_imperio`.`estabelecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_imperio`.`estabelecimento` (
  `idestabelecimento` INT NOT NULL AUTO_INCREMENT,
  `tipo_estabelecimento_idtipo_estabelecimento` INT NOT NULL,
  `estoque_idestoque` INT NOT NULL,
  `nome_estabelecimento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idestabelecimento`),
  INDEX `fk_estabelecimento_tipo_estabelecimento_idx` (`tipo_estabelecimento_idtipo_estabelecimento` ASC) VISIBLE,
  INDEX `fk_estabelecimento_estoque1_idx` (`estoque_idestoque` ASC) VISIBLE,
  CONSTRAINT `fk_estabelecimento_tipo_estabelecimento`
    FOREIGN KEY (`tipo_estabelecimento_idtipo_estabelecimento`)
    REFERENCES `sis_imperio`.`tipo_estabelecimento` (`idtipo_estabelecimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estabelecimento_estoque1`
    FOREIGN KEY (`estoque_idestoque`)
    REFERENCES `sis_imperio`.`estoque` (`idestoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis_imperio`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_imperio`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `estabelecimento_idestabelecimento` INT NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `fk_cliente_estabelecimento1_idx` (`estabelecimento_idestabelecimento` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_estabelecimento1`
    FOREIGN KEY (`estabelecimento_idestabelecimento`)
    REFERENCES `sis_imperio`.`estabelecimento` (`idestabelecimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis_imperio`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_imperio`.`tipo_usuario` (
  `idtipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `tipoUsuario` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis_imperio`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_imperio`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `tipo_usuario_idtipo_usuario` INT NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_tipo_usuario1_idx` (`tipo_usuario_idtipo_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tipo_usuario1`
    FOREIGN KEY (`tipo_usuario_idtipo_usuario`)
    REFERENCES `sis_imperio`.`tipo_usuario` (`idtipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis_imperio`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_imperio`.`funcionario` (
  `idfuncionarios` INT NOT NULL AUTO_INCREMENT,
  `usuario_idfuncionario` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` INT NOT NULL,
  `foto` VARCHAR(255) NOT NULL,
  `documento` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idfuncionarios`),
  INDEX `fk_funcionario_usuario1_idx` (`usuario_idfuncionario` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_usuario1`
    FOREIGN KEY (`usuario_idfuncionario`)
    REFERENCES `sis_imperio`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis_imperio`.`comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_imperio`.`comanda` (
  `idcomanda` INT NOT NULL AUTO_INCREMENT,
  `cliente_idcliente` INT NOT NULL,
  `funcionario_idfuncionarios` INT NOT NULL,
  `estabelecimento_idestabelecimento` INT NOT NULL,
  PRIMARY KEY (`idcomanda`),
  INDEX `fk_comanda_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  INDEX `fk_comanda_funcionario1_idx` (`funcionario_idfuncionarios` ASC) VISIBLE,
  INDEX `fk_comanda_estabelecimento1_idx` (`estabelecimento_idestabelecimento` ASC) VISIBLE,
  CONSTRAINT `fk_comanda_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `sis_imperio`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comanda_funcionario1`
    FOREIGN KEY (`funcionario_idfuncionarios`)
    REFERENCES `sis_imperio`.`funcionario` (`idfuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comanda_estabelecimento1`
    FOREIGN KEY (`estabelecimento_idestabelecimento`)
    REFERENCES `sis_imperio`.`estabelecimento` (`idestabelecimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis_imperio`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_imperio`.`reserva` (
  `idreserva` INT NOT NULL AUTO_INCREMENT,
  `estabelecimento_idestabelecimento` INT NOT NULL,
  PRIMARY KEY (`idreserva`),
  INDEX `fk_reserva_estabelecimento1_idx` (`estabelecimento_idestabelecimento` ASC) VISIBLE,
  CONSTRAINT `fk_reserva_estabelecimento1`
    FOREIGN KEY (`estabelecimento_idestabelecimento`)
    REFERENCES `sis_imperio`.`estabelecimento` (`idestabelecimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis_imperio`.`itens_reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_imperio`.`itens_reserva` (
  `iditens_reserva` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` FLOAT NOT NULL,
  `tempo` INT NOT NULL,
  PRIMARY KEY (`iditens_reserva`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis_imperio`.`item_comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_imperio`.`item_comanda` (
  `iditem_comanda` INT NOT NULL AUTO_INCREMENT,
  `nome_item` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iditem_comanda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis_imperio`.`usuario_has_estabelecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_imperio`.`usuario_has_estabelecimento` (
  `usuario_idfuncionario` INT NOT NULL,
  `estabelecimento_idestabelecimento` INT NOT NULL,
  PRIMARY KEY (`usuario_idfuncionario`, `estabelecimento_idestabelecimento`),
  INDEX `fk_usuario_has_estabelecimento_estabelecimento1_idx` (`estabelecimento_idestabelecimento` ASC) VISIBLE,
  INDEX `fk_usuario_has_estabelecimento_usuario1_idx` (`usuario_idfuncionario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_estabelecimento_usuario1`
    FOREIGN KEY (`usuario_idfuncionario`)
    REFERENCES `sis_imperio`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_estabelecimento_estabelecimento1`
    FOREIGN KEY (`estabelecimento_idestabelecimento`)
    REFERENCES `sis_imperio`.`estabelecimento` (`idestabelecimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis_imperio`.`reserva_has_itens_reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_imperio`.`reserva_has_itens_reserva` (
  `reserva_idreserva` INT NOT NULL,
  `itens_reserva_iditens_reserva` INT NOT NULL,
  PRIMARY KEY (`reserva_idreserva`, `itens_reserva_iditens_reserva`),
  INDEX `fk_reserva_has_itens_reserva_itens_reserva1_idx` (`itens_reserva_iditens_reserva` ASC) VISIBLE,
  INDEX `fk_reserva_has_itens_reserva_reserva1_idx` (`reserva_idreserva` ASC) VISIBLE,
  CONSTRAINT `fk_reserva_has_itens_reserva_reserva1`
    FOREIGN KEY (`reserva_idreserva`)
    REFERENCES `sis_imperio`.`reserva` (`idreserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_has_itens_reserva_itens_reserva1`
    FOREIGN KEY (`itens_reserva_iditens_reserva`)
    REFERENCES `sis_imperio`.`itens_reserva` (`iditens_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis_imperio`.`comanda_has_item_comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_imperio`.`comanda_has_item_comanda` (
  `comanda_idcomanda` INT NOT NULL,
  `item_comanda_iditem_comanda` INT NOT NULL,
  PRIMARY KEY (`comanda_idcomanda`, `item_comanda_iditem_comanda`),
  INDEX `fk_comanda_has_item_comanda_item_comanda1_idx` (`item_comanda_iditem_comanda` ASC) VISIBLE,
  INDEX `fk_comanda_has_item_comanda_comanda1_idx` (`comanda_idcomanda` ASC) VISIBLE,
  CONSTRAINT `fk_comanda_has_item_comanda_comanda1`
    FOREIGN KEY (`comanda_idcomanda`)
    REFERENCES `sis_imperio`.`comanda` (`idcomanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comanda_has_item_comanda_item_comanda1`
    FOREIGN KEY (`item_comanda_iditem_comanda`)
    REFERENCES `sis_imperio`.`item_comanda` (`iditem_comanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sis_imperio`.`item_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sis_imperio`.`item_estoque` (
  `iditem_estoque` INT NOT NULL AUTO_INCREMENT,
  `estoque_idestoque` INT NOT NULL,
  `nome_item` VARCHAR(45) NOT NULL,
  `preco` FLOAT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`iditem_estoque`),
  INDEX `fk_item_estoque_estoque1_idx` (`estoque_idestoque` ASC) VISIBLE,
  CONSTRAINT `fk_item_estoque_estoque1`
    FOREIGN KEY (`estoque_idestoque`)
    REFERENCES `sis_imperio`.`estoque` (`idestoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
